AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  gestalt
  
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs12.x
    MemorySize: 1536
    Environment:
        Variables:
          REGION: !Ref 'AWS::Region'
          STAGE: !Sub '${Stage}'

Resources:
  AuthConfigDynamoDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub
        - ${Stack}-auth
        - { Stack: !Ref 'AWS::StackName' }
      KeySchema:
        - AttributeName: token 
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: token
          AttributeType: S
      BillingMode: PAY_PER_REQUEST

  ClientOverridesDynamoDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub
        - ${Stack}-clients
        - { Stack: !Ref 'AWS::StackName' }
      KeySchema:
        - AttributeName: client_id 
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: client_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST

  ConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref 'AWS::StackName'

  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      EndpointConfiguration: EDGE
      Name: !Ref 'AWS::StackName'
      Cors:
        AllowMethods: "'GET,PUT,POST,DELETE,HEAD,OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
        AllowCredentials: "'*'"
      Domain:
        EndpointConfiguration: EDGE
        DomainName: !Sub '${Domain}'
        CertificateArn: !Sub '${CertificateArn}'
        Route53:
          HostedZoneId: !Sub '${ZoneId}'
      Auth:
        DefaultAuthorizer: LambdaTokenAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          LambdaTokenAuthorizer:
            FunctionArn: !GetAtt Authorizer.Arn
            Identity:
              ValidationExpression: ^Bearer [-0-9a-zA-z\.]*
              ReauthorizeEvery: 3600
              Headers:
                - Authorization

  GetConfigFunction:
    Type: AWS::Serverless::Function
    DependsOn: 'ConfigBucket'
    Properties:
      FunctionName: !Sub
        - ${Stack}-get-config
        - { Stack: !Ref 'AWS::StackName' }
      CodeUri: handlers/get-config/
      Handler: src/index.default
      Events:
        GetConfig:
          Type: Api 
          Properties:
            Path: /
            Method: get
            RestApiId: !Ref ApiGatewayApi
            RequestParameters:
              - method.request.querystring.version:
                  Required: false
                  Caching: false
              - method.request.querystring.key:
                  Required: false
                  Caching: false
              - method.request.querystring.client_id:
                  Required: false
                  Caching: false
              - method.request.header.Authorization:
                  Required: true
                  Caching: false
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref 'AWS::StackName'
        - DynamoDBCrudPolicy:
            TableName: !Ref ClientOverridesDynamoDB
      Environment:
        Variables:
          CONFIG_BUCKET: !Ref 'AWS::StackName'
          CLIENT_TABLE: !Ref ClientOverridesDynamoDB

  CreateClientConfigFunction:
    Type: AWS::Serverless::Function
    DependsOn: 'ConfigBucket'
    Properties:
      FunctionName: !Sub
        - ${Stack}-create-client
        - { Stack: !Ref 'AWS::StackName' }
      CodeUri: handlers/create-client-config/
      Handler: src/index.default
      Events:
        CustomConfig:
          Type: Api 
          Properties:
            Path: /client/{client_id}
            Method: post
            RestApiId: !Ref ApiGatewayApi
            RequestParameters:
              - method.request.path.client_id:
                  Required: true
                  Caching: true
              - method.request.header.Authorization:
                  Required: true
                  Caching: false
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ClientOverridesDynamoDB
      Environment:
        Variables:
          CLIENT_TABLE: !Ref ClientOverridesDynamoDB

  UpdatelientConfigFunction:
    Type: AWS::Serverless::Function
    DependsOn: 'ConfigBucket'
    Properties:
      FunctionName: !Sub
        - ${Stack}-update-client
        - { Stack: !Ref 'AWS::StackName' }
      CodeUri: handlers/update-client-config/
      Handler: src/index.default
      Events:
        UpdateCustomConfig:
          Type: Api 
          Properties:
            Path: /client/{client_id}
            Method: put
            RestApiId: !Ref ApiGatewayApi
            RequestParameters:
              - method.request.path.client_id:
                  Required: true
                  Caching: true
              - method.request.header.Authorization:
                  Required: true
                  Caching: false
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ClientOverridesDynamoDB
      Environment:
        Variables:
          CLIENT_TABLE: !Ref ClientOverridesDynamoDB

  Authorizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref AuthConfigDynamoDB
      CodeUri: handlers/authorizer/
      Handler: src/index.default
      Environment:
        Variables:
          TOKEN_TABLE: !Ref AuthConfigDynamoDB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthConfigDynamoDB

Parameters:
  ZoneId:
    Type: String
    Description: The Zone Id to generate the sub domain within

  Domain:
    Type: String
    Description: The domain of our api

  CertificateArn:
    Type: String
    Description: The certifcate arn for use in creating the api 

  Stage:
    Type: String
    Default: dev
    Description: The env where the application is running in, e.g., dev, prod.
    AllowedValues:
      - prod
      - dev
